
PUT http://localhost:5000/api/movies/update
Content-Type: application/json


{
    "id":"678d8dd86fcb7a2089b505d3",
    "movieId":"Shrek",
    "isFavorite":false
}



GET http://localhost:5000/api/movies/contains?id=678d8dd86fcb7a2089b505d3&movieId=tt0126029&type=favorites


GET http://localhost:5000/api/movies/contains?id=678d8dd86fcb7a2089b505d3&movieId=tt0126029&type=bookmarks